# -*- coding: utf-8 -*-
"""compiler_phases_combined.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FhikN2aRwre9PY2hWylZZLoeKKsmso05
"""

import pandas as pd
import os

# Lexical Analysis

keywords = {'int', 'float', 'string', 'char', 'void', 'bool',
           'if', 'else', 'switch', 'case', 'default',
           'while', 'for', 'do', 'break', 'continue',
           'true', 'false', 'return', 'class', 'public',
           'private', 'protected', 'new'}

operators = {'<', '>', '=', '!',
             '<=', '>=', '!=', '==',
             '&&', '||',
             '+', '-', '*', '/', '%',
             '.', '::'}

separators = {'(', ')', '{', '}', ';', ',', '[', ']'}

tokens = []

def lexical(code):
    print("Starting Lexical Analysis...")
    i = 0
    n = len(code)
    tokens.clear()

    while i < n:
        ch = code[i]

        # Skip whitespace
        if ch.isspace():
            i += 1
            continue

        # Skip comments // or /*.....*/
        if code[i:i+2] == '//':
            i += 2
            while i < n and code[i] != '\n':
                i += 1
            continue
        if code[i:i+2] == '/*':
            i += 2
            while i < n and code[i:i+2] != '*/':
                i += 1
            i += 2
            continue

        # String Literals
        if ch == '"':
            start = i
            i += 1
            while i < n and code[i] != '"':
                i += 1
            if i < n:
                tokens.append(('LITERAL', code[start+1:i]))
                i += 1
            continue

        # Keywords and Identifiers
        if ch.isalpha() or ch == '_':
            start = i
            while i < n and (code[i].isalpha() or code[i].isdigit() or code[i] == '_'):
                i += 1
            word = code[start:i]
            if word in keywords:
                tokens.append((word, word))
            else:
                tokens.append(('IDENTIFIER', word))
            continue

        # Numbers
        if ch.isdigit():
            start = i
            while i < n and (code[i].isdigit() or code[i] == '.'):
                i += 1
            num = code[start:i]
            tokens.append(('NUMBER', num))
            continue

        # 2 and 1 char Operators
        if i + 1 < n and code[i:i+2] in operators:
            tokens.append(('OPERATOR', code[i:i+2]))
            i += 2
            continue
        if ch in operators:
            tokens.append(('OPERATOR', ch))
            i += 1
            continue

        # Separators
        if ch in separators:
            tokens.append((ch, ch))
            i += 1
            continue

        # Unknown
        tokens.append(('UNKNOWN', ch))
        i += 1

    tokens.append(('EOF', 'EOF'))
    print(f"Lexical Analysis Complete. Found {len(tokens)} tokens.")
    return tokens

# SYNTAX ANALYSIS & METRICS

pos = 0

# Symbol Table

symbol_table = [{}]
all_symbols = []

def define_symbol(name, type_val):
    symbol_table[-1][name] = type_val
    all_symbols.append({'name': name, 'type': type_val, 'scope_level': len(symbol_table)})

def enter_scope():
    symbol_table.append({})

def exit_scope():
    symbol_table.pop()

# Metrics Global Variables
metrics = {
    'FUNC_LOC': 0,
    'PARAM_COUNT': 0,
    'LOOP_COUNT': 0,
    'IF_COUNT': 0,
    'MAX_NEST_DEPTH': 0,
    'CYCLO_COMPLEXITY': 1,
    'CLASS_LOC': 0,
    'METHOD_COUNT': 0,
    'FIELD_COUNT': 0,
    'EXTERNAL_REF_COUNT': 0
}

current_nesting = 0
in_function = False

def peek():
    return tokens[pos]

def advance():
    global pos
    pos += 1

def match(expected):
    token = peek()
    if token[0] == expected:
        advance()
    elif token[0] == 'OPERATOR' and token[1] == expected:
        advance()
    else:
        print(f"Syntax Error: Expected {expected} but got {token[0]} at pos {pos}")
        raise ValueError(f"Expected {expected} but got {token}")

def parse_program():
    print("\nStarting Syntax Analysis & Metric Extraction...")
    global pos
    while peek()[0] != 'EOF':
        if peek()[0] == 'class':
            parse_class()
        elif peek()[0] in ('int', 'float', 'void', 'string', 'bool', 'char'):
            save_pos = pos
            parse_type()
            match('IDENTIFIER')
            if peek()[0] == '(':
                pos = save_pos
                parse_function()
            else:
                pos = save_pos
                parse_declaration()
        else:
            print(f"Skipping unknown token at global scope: {peek()}")
            advance()
    print("Syntax Analysis Complete.")

def parse_class():
    global pos
    match('class')
    class_name = peek()[1]
    match('IDENTIFIER')
    define_symbol(class_name, 'CLASS')
    match('{')

    # Simple class body parsing
    while peek()[0] != '}' and peek()[0] != 'EOF':
        if peek()[0] in ('public', 'private', 'protected'):
            match(peek()[0])
            if peek()[0] == ':':
                 advance()
            pass

        if peek()[0] in ('int', 'float', 'void', 'string', 'bool', 'char'):
             # Method or Field
            save_pos = pos
            parse_type()
            match('IDENTIFIER')
            if peek()[0] == '(':
                # Method
                metrics['METHOD_COUNT'] += 1
                pos = save_pos
                parse_function()
            else:
                # Field
                metrics['FIELD_COUNT'] += 1
                # Parse declaration
                pos = save_pos
                parse_declaration()
        else:
             advance()

    match('}')
    match(';')
    metrics['CLASS_LOC'] += 1

def parse_function():
    global current_nesting, in_function

    # Type IDENTIFIER ( Params ) { Body }
    # Get return type
    ret_type = peek()[1] if peek()[0] != 'IDENTIFIER' else peek()[1]
    parse_type()

    func_name = peek()[1]
    match('IDENTIFIER')

    # Define function in current scope (global or class)
    define_symbol(func_name, ret_type)

    match('(')

    # Enter scope for parameters
    enter_scope()

    # Count params
    p_count = 0
    if peek()[0] != ')':
        while True:
            p_type = peek()[1]
            parse_type()
            p_name = peek()[1]
            match('IDENTIFIER')

            # Define param in function scope
            define_symbol(p_name, p_type)

            p_count += 1
            if peek()[0] == ',':
                match(',')
            else:
                break
    metrics['PARAM_COUNT'] = max(metrics['PARAM_COUNT'], p_count)

    match(')')

    match('{')
    in_function = True
    current_nesting = 0

    # Parse body
    stmt_count = 0
    while peek()[0] != '}':
        parse_statement()
        stmt_count += 1

    metrics['FUNC_LOC'] += stmt_count
    match('}')

    exit_scope() # End function scope
    in_function = False

def parse_type():
    if peek()[0] in ('int', 'float', 'char', 'void', 'string', 'bool'):
        advance()
    elif peek()[0] == 'IDENTIFIER': # Class types
        advance()
    else:
        raise ValueError(f"Expected type, got {peek()}")

def parse_statement():
    global pos
    if peek()[0] in ('int', 'float', 'char', 'string', 'bool', 'IDENTIFIER'):
        # Could be Decl or Assign or Call
        # Heuristic: if type keyword -> Decl. If Identifier -> Assign or Call
        if peek()[0] == 'IDENTIFIER':
             # Check next
             save_pos = pos
             match('IDENTIFIER')
             if peek()[0] == '(':
                  # Call
                  metrics['EXTERNAL_REF_COUNT'] += 1
                  pos = save_pos
                  parse_call()
             elif (peek()[0] == 'OPERATOR' and peek()[1] == '=') or (peek()[0] == 'OPERATOR' and peek()[1] == '.'):
                  # Assign
                  pos = save_pos
                  parse_assignment()
             else:
                  # Maybe declaration with custom type?
                  pos = save_pos
                  parse_declaration()
        else:
             parse_declaration()

    elif peek()[0] == 'return':
        match('return')
        # Simplified expression parsing
        while peek()[0] != ';':
            advance()
        match(';')
    elif peek()[0] == 'if':
        metrics['IF_COUNT'] += 1
        metrics['CYCLO_COMPLEXITY'] += 1
        parse_if()
    elif peek()[0] == 'while':
        metrics['LOOP_COUNT'] += 1
        metrics['CYCLO_COMPLEXITY'] += 1
        parse_while()
    elif peek()[0] == 'for':
        metrics['LOOP_COUNT'] += 1
        metrics['CYCLO_COMPLEXITY'] += 1
        parse_for()
    elif peek()[0] == '{':
        parse_block()
    else:
        advance()

def parse_block():
    global current_nesting
    match('{')
    current_nesting += 1
    metrics['MAX_NEST_DEPTH'] = max(metrics['MAX_NEST_DEPTH'], current_nesting)

    while peek()[0] != '}':
        parse_statement()

    match('}')
    current_nesting -= 1

def parse_if():
    match('if')
    match('(')
    parse_expression_skip()
    match(')')
    parse_statement() # Or block
    if peek()[0] == 'else':
        match('else')
        parse_statement()

def parse_while():
    match('while')
    match('(')
    parse_expression_skip()
    match(')')
    parse_statement()

def parse_for():
    match('for')
    match('(')
    # Init
    while peek()[0] != ';': advance()
    match(';')
    # Condition
    while peek()[0] != ';': advance()
    match(';')
    # Incr
    while peek()[0] != ')': advance()
    match(')')
    parse_statement()

def parse_call():
    match('IDENTIFIER')
    match('(')
    # Skip args
    while peek()[0] != ')':
        advance()
    match(')')
    match(';')

def parse_assignment():
    # ID = expr ; or ID.field = expr ;
    match('IDENTIFIER')
    if peek()[0] == 'OPERATOR' and peek()[1] == '.':
        match('.')
        match('IDENTIFIER')

    if peek()[0] == 'OPERATOR' and peek()[1] == '=':
        match('=')
        parse_expression_skip()
        match(';')
    else:
        while peek()[0] != ';': advance()
        match(';')

def parse_declaration():
    # Type ID ; or Type ID = expr;
    var_type = peek()[1]
    parse_type()

    var_name = peek()[1]
    match('IDENTIFIER')

    # Define variable in current scope
    define_symbol(var_name, var_type)

    if peek()[0] == 'OPERATOR' and peek()[1] == '=':
        match('=')
        parse_expression_skip()
    match(';')

def parse_expression_skip():
    # Skip until delimiter ')' or ';' or ','
    while peek()[0] not in (';', ')', ',', '}'):
        advance()

def parse_expression():
    parse_expression_skip()

import pickle
import os

from google.colab import drive
drive.mount('/content/drive')

Model_path = "/content/drive/MyDrive/model.pkl"
if os.path.exists(Model_path):
  with open(Model_path , 'rb') as f:
    smell_model = pickle.load(f)
    print("Model loaded successfully")
else:
  smell_model = None
  print("Model not found")

# MAIN EXECUTION

code_sample = """
class DataProcessor {
public:
    int status;
    int count;
    int total;
    int errorCode;
    int mode;

    int processData(int a, int b, int c, int d, int e, int f, int g) {
        int result = 0;
        int temp = 0;

        if (a > 0) {
            if (b > 0) {
                for (int i = 0; i < a; i++) {
                    if (i % 2 == 0) {
                        for (int j = 0; j < b; j++) {
                            if (j > 3) {
                                result += i * j;
                                temp = result + c;
                            }
                        }
                    }
                }

                if (c > 10) {
                    result = result + c;
                }
                if (d < 0) {
                    result = result - d;
                }
                if (e == 0) {
                    result = result * 2;
                }

            } else {
                for (int k = 0; k < g; k++) {
                    if (k % 3 == 0) {
                        result += k;
                    } else if (k % 2 == 0) {
                        result -= k;
                    }
                }
            }
        }

        if (f > 100) {
            while (temp > 0) {
                temp--;
                result += temp;
            }
        }

        if (result < 0) {
            errorCode = -1;
        } else if (result > 1000) {
            errorCode = 2;
        } else {
            errorCode = 0;
        }

        status = result;
        return result;
    }
};

int main() {
    DataProcessor dp;
    int out = dp.processData(5, 3, 15, -2, 0, 200, 4);
    cout << "Result: " << out << endl;
    return 0;
}
"""

print("--- [Combined Compiler Phases] ---")

# 1. Lexical Analysis
lexical(code_sample)

# 2. Syntax Analysis & Metrics
metrics = {
    'FUNC_LOC': 0,
    'PARAM_COUNT': 0,
    'LOOP_COUNT': 0,
    'IF_COUNT': 0,
    'MAX_NEST_DEPTH': 0,
    'CYCLO_COMPLEXITY': 1,
    'CLASS_LOC': 0,
    'METHOD_COUNT': 0,
    'FIELD_COUNT': 0,
    'EXTERNAL_REF_COUNT': 0
}
pos = 0
symbol_table = [{}]
all_symbols.clear()

try:
    parse_program()
except Exception as e:
    print(f"Parsing failed: {e}")

# 3. Output Symbol Table
print("\n--- Symbol Table ---")
print(f"{'Name':<20} {'Type':<10} {'Scope Level':<10}")
print("-" * 40)
for sym in all_symbols:
    print(f"{sym['name']:<20} {sym['type']:<10} {sym['scope_level']:<10}")

# 3. Output Metrics
print("\n--- Extracted Metrics ---")
for key, val in metrics.items():
    print(f"{key}: {val}")

# 4. ML-Based Code Smell Detection (Week 7)
print("\n--- ML-Based Code Smell Detection ---")
FEATURES = ['FUNC_LOC', 'PARAM_COUNT', 'LOOP_COUNT', 'IF_COUNT',
            'MAX_NEST_DEPTH', 'CYCLO_COMPLEXITY', 'CLASS_LOC',
            'METHOD_COUNT', 'FIELD_COUNT', 'EXTERNAL_REF_COUNT']
feature_values = [[metrics[f] for f in FEATURES]]
if smell_model:
    prediction = smell_model.predict(feature_values)[0]
    probability = smell_model.predict_proba(feature_values)[0]
    smell_detected = int(prediction)
    print(f"Prediction: {'SMELLY CODE [WARNING]' if prediction == 1 else 'CLEAN CODE [OK]'}")
    print(f"Confidence: Clean={probability[0]:.2f}, Smelly={probability[1]:.2f}")
else:
    # Fallback to threshold rules
    if metrics['MAX_NEST_DEPTH'] > 2 or metrics['CYCLO_COMPLEXITY'] > 5:
        print("RESULT: Smelly Code Detected (Threshold Fallback) [WARNING]")
        smell_detected = 1
    else:
        print("RESULT: Clean Code (Threshold Fallback) [OK]")
        smell_detected = 0

# 5. Generate Feature Dataset (Week 6 Requirement)
print("\n--- Generating Feature Dataset ---")
df = pd.DataFrame([metrics])
df['LABEL'] = smell_detected #

output_csv = "dataset.csv"
if os.path.exists(output_csv):
    df.to_csv(output_csv, mode='a', header=False, index=False)
    print(f"Appended metrics to existing '{output_csv}'")
else:
    df.to_csv(output_csv, index=False)
    print(f"Created new '{output_csv}' with extracted features")

