# -*- coding: utf-8 -*-
"""Metrics_Extraction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lWwgKs1Mm1aRHNEwhSLq8KX-9UPfV1Gd
"""

!pip install lizard
import re
import lizard
import os
import pickle
import sys
import pandas as pd
import joblib

class MetricExtractor:
  def __init__(self , file_path):
    self.file_path = file_path
    with open(file_path, 'r', encoding='utf-8' , errors ='ignore') as f:
      self.code = f.read()
    self.lines = self.code.split("\n")
    self.metrics = {}

  def extract_metrics(self):
    analysis = lizard.analyze_file(self.file_path)

    #1. Non_Comment Lines in Code
    self.metrics['FUNC_LOC'] = analysis.nloc

    #2.Max parameters found in any function
    if analysis.function_list:
      self.metrics['PARAM_COUNT'] = max(f.parameter_count for f in analysis.function_list)
    else:
      self.metrics['PARAM_COUNT'] = 0

    #3
    self.metrics['LOOP_COUNT'] = len(re.findall(r'\b(for|while|do)\b', self.code))

    #4
    self.metrics['IF_COUNT'] = len(re.findall(r'\b(if|else)\b', self.code))

    #5 MAX NEST DEPTH : Using the braces
    current_depth = 0
    max_depth = 0
    for char in self.code:
      if char == '{':
        current_depth += 1
        if current_depth > max_depth:
          max_depth = current_depth
      elif char == '}':
        current_depth -= 1
    self.metrics['MAX_NEST_DEPTH'] = max_depth

    #6
    if analysis.function_list:
      self.metrics['CYCLO_COMPLEXITY'] = max(f.cyclomatic_complexity for f in analysis.function_list)
    else:
      self.metrics['CYCLO_COMPLEXITY'] = 1

    #7
    self.metrics['CLASS_LOC'] = 0
    if 'class ' in self.code:
      self.metrics['CLASS_LOC'] = len(self.lines)

    #8
    self.metrics['METHOD_COUNT'] = len(analysis.function_list)

    #9
    self.metrics['FIELD_COUNT'] = 5

    #10
    calls = len(re.findall(r'\b\w+\(', self.code))
    self.metrics['EXTERNAL_REF_COUNT'] = calls

    return self.metrics

def analyze_code(file_path):
  print(f"Analyzing file: {file_path}")
  print("File size:", os.path.getsize(file_path))

  if not os.path.exists(file_path):
    print("Error: File not found.")
    return

  extractor = MetricExtractor(file_path)
  metrics = extractor.extract_metrics()
  print("Extracted Features:")
  for i , j in metrics.items():
    print(f"{i}: {j}")

  feature_order = ['FUNC_LOC', 'PARAM_COUNT', 'LOOP_COUNT', 'IF_COUNT', 'MAX_NEST_DEPTH',
        'CYCLO_COMPLEXITY', 'CLASS_LOC', 'METHOD_COUNT', 'FIELD_COUNT',
        'EXTERNAL_REF_COUNT']

  features_df = pd.DataFrame([metrics])

  for col in feature_order:
    if col not in features_df.columns:
      features_df[col] = 0

  features_df = features_df[feature_order]


  from google.colab import drive
  drive.mount('/content/drive')

  Model_path = "/content/drive/MyDrive/model.pkl"
  if os.path.exists(Model_path):
    with open(Model_path , 'rb') as f:
      smell_model = pickle.load(f)
      print("Model loaded successfully")
  else:
    smell_model = None
    print("Model not found")
    return

  prediction = smell_model.predict(features_df)[0]

  print("\n")

  if prediction == 1:
    print(f"RESULT: SMELLY CODE DETECTED [!]")
  else:
    print("RESULT: CLEAN CODE [v]")

if __name__ == "__main__":
  if len(sys.argv) < 2 or sys.argv[1] == '-f':
    print("Usage: python Metrics_Extraction.py <path_to_cpp_file>")

    dummy_file = "test_code.cpp"
    with open(dummy_file, "w") as f:
      f.write("""
      #include <iostream>
            void complexFunction() {
                int x = 0;
                if (x < 10) {
                    for(int i=0; i<10; i++) {
                        if (i % 2 == 0) {
                            cout << i;
                        }
                    }
                }
            }
      """)

    print(f"No file provided. Created and analyzing '{dummy_file}' for demostration....")
    analyze_code(dummy_file)
  else:
    analyze_code(sys.argv[1])

print(sys.argv)