# -*- coding: utf-8 -*-
"""Training_Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19edHZH9P9za1fme4vC7uBR9hXVPFp-3N
"""

!pip install numpy
!pip install pandas
!pip install matplotlib
!pip install seaborn
!pip install scikit-learn

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.metrics import accuracy_score , classification_report
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score
import joblib

# %matplotlib inline

import warnings
warnings.filterwarnings('ignore')

import pandas as pd
df = pd.read_csv("dataset.csv")
df.head()
print(df.columns)

FEATURES = ['FUNC_LOC', 'PARAM_COUNT', 'LOOP_COUNT', 'IF_COUNT', 'MAX_NEST_DEPTH', 'CYCLO_COMPLEXITY', 'CLASS_LOC', 'METHOD_COUNT', 'FIELD_COUNT', 'EXTERNAL_REF_COUNT']
x = df[FEATURES]
y = df["LABEL"]
X_train , X_test , y_train , y_test = train_test_split(x , y, test_size=0.2 , random_state=42)

N_observations , N_features = x.shape
#print('Number of Observations: ' + str(N_observations))
print('Number of Features: ' + str(N_features))

n_estimators = 100
rf = RandomForestClassifier(n_estimators = n_estimators,max_depth = 5 , random_state = 42)
rf.fit(X_train, y_train)

y_pred = rf.predict(X_test)


scores = cross_val_score(rf, x, y, cv=5, scoring='accuracy')
print(f"Cross-Validation Accuracy: {scores.mean():.2f} \u00b1 {scores.std():.2f}")

import pickle

joblib.dump(rf, "smell_model.pkl")

from google.colab import drive
drive.mount('/content/drive')
model_path = "/content/drive/MyDrive/model.pkl"

with open(model_path, 'wb') as f:
    pickle.dump(rf, f)
print("Model saved as 'smell_model.pkl'")